# Generated by Django 5.2.17 on 2026-08-18 11:26

from django.db import migrations, models

OLD_TO_NEW = {
    'tab1': 'build_model',
    'tab2': 'run_analysis',
    'tab3': 'post_processing',
    'tab4': 'design',
}
NEW_TO_OLD = {v: k for k, v in OLD_TO_NEW.items()}


def rename_tabs_forward(apps, schema_editor):
    ChatMessage = apps.get_model('ai_chat', 'ChatMessage')
    OutputBundle = apps.get_model('ai_chat', 'OutputBundle')
    for old, new in OLD_TO_NEW.items():
        ChatMessage.objects.filter(tab=old).update(tab=new)
        OutputBundle.objects.filter(tab=old).update(tab=new)


def rename_tabs_backward(apps, schema_editor):
    ChatMessage = apps.get_model('ai_chat', 'ChatMessage')
    OutputBundle = apps.get_model('ai_chat', 'OutputBundle')
    for new, old in NEW_TO_OLD.items():
        ChatMessage.objects.filter(tab=new).update(tab=old)
        OutputBundle.objects.filter(tab=new).update(tab=old)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_embeddingsettings_sourcedocument_sourcechunk'),
    ]

    operations = [
        # Widen the column and remap any existing tab1..tab4 rows to the
        # new keys BEFORE the choices metadata changes, so existing chat
        # history under the old tab keys doesn't become inaccessible
        # (views.py's VALID_TABS is derived straight from TAB_CHOICES).
        migrations.AlterField(
            model_name='chatmessage',
            name='tab',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outputbundle',
            name='tab',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(rename_tabs_forward, rename_tabs_backward),
        migrations.AlterField(
            model_name='chatmessage',
            name='tab',
            field=models.CharField(choices=[('build_model', 'Build Model'), ('run_analysis', 'Run Analysis'), ('post_processing', 'Post Processing'), ('design', 'Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outputbundle',
            name='tab',
            field=models.CharField(choices=[('build_model', 'Build Model'), ('run_analysis', 'Run Analysis'), ('post_processing', 'Post Processing'), ('design', 'Design')], max_length=20),
        ),
    ]
